version: "3.0"

services:
  web:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./ssl:/certs
      - ./src:/usr/share/nginx/html
      - ./nginx:/etc/nginx/conf.d